const constants = {
    FETCH_LOGIN: "FETCH_LOGIN",
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    FAIL_LOGIN: "FAIL_LOGIN",
    DISCONNECT: "DISCONNECT",
    TRANSLATE: "TRANSLATE",
    FUNCTIONALITY: "FUNCTIONALITY",
    PUSH: "PUSH",
    SUCCESS_UPDATE_PROFILE: "SUCCESS_UPDATE_PROFILE",
    ERROR_UPDATE_PROFILE: "ERROR_UPDATE_PROFILE",
    WAIT_UPDATE_PROFILE: "WAIT_UPDATE_PROFILE",
    NB_USERS: "NB_USERS"
};

export default constants;